/**
 * Tests for the rationale-provenance predicate (#444).
 *
 * Every tier is pinned by name, including the #435-era bridge —
 * deleting that clause silently hides sound rationales rather
 * than failing loudly, which is precisely the class of change
 * this issue exists to make visible.
 */

import { describe, expect, it } from "vitest";

import type { ScoreComponents } from "../../types/capability.ts";

import {
  isRationaleTrustworthy,
  RATIONALE_GATED_SCHEMA_VERSION,
} from "./matchProvenance.ts";

const APPLICABILITY: Readonly<Record<keyof ScoreComponents, boolean>> = {
  semantic_similarity: true,
  skill_overlap: true,
  domain_overlap: true,
  tool_overlap: true,
  seniority_alignment: true,
  scope_alignment: true,
  recency: true,
};

describe("isRationaleTrustworthy: the four tiers", () => {
  it("pre-#131 (nothing persisted) is not trustworthy", () => {
    expect(isRationaleTrustworthy({})).toBe(false);
  });

  it("pre-#435 (components, no applicability) is not trustworthy", () => {
    // `components` alone says nothing about how the prose was
    // produced — these rows were generated by a
    // `pickDrivingComponent` with no applicability filter, so a
    // no-constraint neutral could win the tie-break and emit
    // "matched on skill overlap" for an axis never compared.
    expect(
      isRationaleTrustworthy({ component_applicability: undefined }),
    ).toBe(false);
  });

  it("#435-era (applicability, no version) IS trustworthy — the bridge", () => {
    // The clause that cannot be deleted yet. These rows were
    // generated under the gated rule and carry no version,
    // because the version did not exist. Removing this line
    // would hide sound rationales with no test failing, which is
    // why it is asserted by name.
    expect(
      isRationaleTrustworthy({ component_applicability: APPLICABILITY }),
    ).toBe(true);
  });

  it("post-#444 (versioned) is trustworthy on the version alone", () => {
    // Load-bearing: no `component_applicability` in this fixture.
    // If the predicate still depended on it, this fails — which
    // is the whole point of the issue.
    expect(
      isRationaleTrustworthy({
        schema_version: RATIONALE_GATED_SCHEMA_VERSION,
      }),
    ).toBe(true);
  });
});

describe("isRationaleTrustworthy: the version comparison", () => {
  it("accepts a future version", () => {
    expect(
      isRationaleTrustworthy({
        schema_version: RATIONALE_GATED_SCHEMA_VERSION + 5,
      }),
    ).toBe(true);
  });

  it("rejects a version below the gated one, applicability aside", () => {
    // A hypothetical version 0 would predate the guarantee. It
    // must not be admitted by the comparison — only by the
    // explicit bridge, and only if it carries applicability.
    expect(
      isRationaleTrustworthy({
        schema_version: RATIONALE_GATED_SCHEMA_VERSION - 1,
      }),
    ).toBe(false);
    expect(
      isRationaleTrustworthy({
        schema_version: RATIONALE_GATED_SCHEMA_VERSION - 1,
        component_applicability: APPLICABILITY,
      }),
    ).toBe(true);
  });
});
