/**
 * Single UnitMatch card. Shipped read-only in #129; this
 * version adds Approve / Reject buttons (#130). Sub-score
 * breakdown ships in #131.
 *
 * Renders:
 *   - The matched Unit's `normalized_summary` as the
 *     headline.
 *   - The `final_score` as a 0–100 number with 1 decimal.
 *   - The `rationale` explaining why the match scores
 *     where it does.
 *   - The `surface_evidence` — the specific piece of
 *     ground-truth content from the Unit being matched.
 *   - Approve / Reject buttons. Visual state is derived
 *     via `approvalStateOf(match)`:
 *       "none"      → "Approve" + "Reject" both clickable
 *       "approved"  → "Approved ✓" (clickable to revert)
 *       "rejected"  → "Rejected ✗" (clickable to revert)
 *
 * Click semantics (single-setter, #133 r1):
 *   - Each click computes the NEXT `MatchApprovalState`
 *     locally and calls `onApprovalStateChange(matchId,
 *     nextState)` once. The container issues exactly one
 *     `updateDoc` per click; per-doc per-client Firestore
 *     write ordering means the LAST submitted write wins
 *     deterministically — no out-of-order race across
 *     offline resync, multi-tab, or rapid double-clicks.
 *   - Approve button: toggles between "approved" and
 *     "none" (revert).
 *   - Reject button: toggles between "rejected" and
 *     "none" (revert).
 *   - Mutual exclusion is structural in the enum:
 *     "approved" and "rejected" are distinct values.
 *     Clicking Approve on a rejected match goes to
 *     "approved" directly; the persisted flag pair
 *     becomes `{ approved_for_use: true, user_rejected:
 *     false }` atomically.
 */

import type { ReactElement } from "react";

import type { ExperienceUnit, UnitMatch } from "../../types/capability.ts";
import {
  approvalStateOf,
  type MatchApprovalState,
} from "../../services/matches.ts";

import MatchScoreBadge from "./MatchScoreBadge.tsx";

export interface MatchCardProps {
  readonly match: UnitMatch;
  readonly unit: ExperienceUnit | null;
  readonly onApprovalStateChange: (
    matchId: string,
    state: MatchApprovalState,
  ) => void;
}

/**
 * Can this match's stored `rationale` / `surface_evidence` be
 * shown as a claim?
 *
 * Only when `component_applicability` is present. Rows written
 * before that field existed were generated by a
 * `pickDrivingComponent` with no applicability filter, so a
 * `0.5` no-constraint neutral could win the tie-break and emit
 * "Matched on skill axis" with the Unit's own skills as
 * evidence — for a comparison that never happened. The
 * breakdown was taught this in #435; the prose beside it was
 * not, so the card contradicted itself: "not evaluated" in the
 * tooltip, "matched on skill overlap" in the Why line.
 *
 * `driving_component` is NOT persisted, so there is no way to
 * ask a legacy row which axis produced its text. Presence of
 * the applicability map is the only available proxy for "this
 * was generated under the gated rule", and it is an exact one:
 * both landed in the same change.
 *
 * Same conservative default `buildBreakdownRows` already
 * applies to these rows. Issue #440.
 *
 * **Deliberately states no remedy.** The obvious copy — "re-run
 * matching to regenerate it" — describes an action that can
 * destroy data. A rematch clear-and-replaces the Role's match
 * set, and Units that are `reembed_pending` are excluded from
 * scoring, so their rows are deleted with no replacement and
 * the user's approve/reject flags on those pairs go with them.
 * Telling someone to trigger that in order to fix a display
 * gap would be advising the worst available action. Flagged by
 * nathanpayne-codex in the Phase 4b review of #438.
 */
function isRationaleTrustworthy(match: UnitMatch): boolean {
  return match.component_applicability !== undefined;
}

export default function MatchCard({
  match,
  unit,
  onApprovalStateChange,
}: MatchCardProps): ReactElement {
  const rationaleIsTrustworthy = isRationaleTrustworthy(match);
  const state = approvalStateOf(match);

  const onClickApprove = () => {
    // Approve toggles between "approved" and "none." If the
    // match was previously "rejected", a single click flips
    // straight to "approved" (mutual exclusion via the enum,
    // not a two-step revert).
    onApprovalStateChange(match.id, state === "approved" ? "none" : "approved");
  };
  const onClickReject = () => {
    onApprovalStateChange(match.id, state === "rejected" ? "none" : "rejected");
  };

  return (
    <article
      className="rounded-md border border-zinc-200 dark:border-zinc-800 p-3 space-y-2 bg-white dark:bg-zinc-900"
      data-testid="match-card"
      data-approval-state={state}
    >
      <header className="flex items-start justify-between gap-3">
        <h4 className="text-sm font-medium leading-5 text-zinc-900 dark:text-zinc-100 flex-1">
          {unit !== null ? (
            unit.normalized_summary
          ) : (
            <span className="italic text-zinc-500">
              (Unit no longer available)
            </span>
          )}
        </h4>
        <MatchScoreBadge
          finalScore={match.final_score}
          components={match.components}
          componentApplicability={match.component_applicability}
          confidence={unit !== null ? unit.confidence_score : null}
        />
      </header>
      {rationaleIsTrustworthy ? (
        <>
          <p className="text-xs text-zinc-600 dark:text-zinc-400">
            <span className="font-medium">Why: </span>
            {match.rationale}
          </p>
          <p className="text-xs text-zinc-600 dark:text-zinc-400">
            <span className="font-medium">Evidence: </span>
            <q className="italic">{match.surface_evidence}</q>
          </p>
        </>
      ) : (
        <p
          className="text-xs italic text-zinc-500"
          data-testid="match-rationale-untrusted"
        >
          Explanation unavailable — this match predates the check that stops a
          rationale describing an axis the engine never evaluated, so its
          stored wording can&rsquo;t be trusted. The score above is unchanged.
        </p>
      )}
      <footer className="flex items-center gap-2 pt-1">
        <button
          type="button"
          onClick={onClickApprove}
          aria-pressed={state === "approved"}
          data-testid="match-approve-button"
          className={
            "rounded px-2 py-1 text-xs font-medium transition-colors " +
            (state === "approved"
              ? "bg-emerald-600 text-white hover:bg-emerald-700 dark:bg-emerald-700 dark:hover:bg-emerald-600"
              : "border border-zinc-300 dark:border-zinc-700 text-zinc-700 dark:text-zinc-300 hover:bg-zinc-100 dark:hover:bg-zinc-800")
          }
        >
          {state === "approved" ? "Approved ✓" : "Approve"}
        </button>
        <button
          type="button"
          onClick={onClickReject}
          aria-pressed={state === "rejected"}
          data-testid="match-reject-button"
          className={
            "rounded px-2 py-1 text-xs font-medium transition-colors " +
            (state === "rejected"
              ? "bg-rose-600 text-white hover:bg-rose-700 dark:bg-rose-700 dark:hover:bg-rose-600"
              : "border border-zinc-300 dark:border-zinc-700 text-zinc-700 dark:text-zinc-300 hover:bg-zinc-100 dark:hover:bg-zinc-800")
          }
        >
          {state === "rejected" ? "Rejected ✗" : "Reject"}
        </button>
      </footer>
    </article>
  );
}
